health_check_port: 8085
server_config:
  processor_mode:
    type: default
    initial_starting_version: 1997824036
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    # At which tx version to start indexing, usually this is the tx version when the contract was deployed
    starting_version: 1997824036
    # At which tx version to stop indexing
    # request_ending_version: 10000
    # Go to https://developers.aptoslabs.com/ to create a project and get an API token
    auth_token: "auth_token_you_can_get_from_aptos_build"
    request_name_header: ""
  db_config:
    type: postgres_config
    # do not include the ?sslmode=require in the connection string when using cloud DB, it will cause an error
    connection_string: "postgresql://username:password@neon_host/db_name"
    # we set db_pool_size to a lower number on cloud because we use a free plan
    db_pool_size: 25
  nft_marketplace_configs:
    - name: "token_activities"
      event_model_mapping:
        # V1 TOKEN EVENT
        0x0000000000000000000000000000000000000000000000000000000000000003::token::MintTokenEvent: mint
        0x0000000000000000000000000000000000000000000000000000000000000003::token::Mint: mint
        0x0000000000000000000000000000000000000000000000000000000000000003::token::BurnTokenEvent: burn
        0x0000000000000000000000000000000000000000000000000000000000000003::token::Burn: burn
        0x0000000000000000000000000000000000000000000000000000000000000003::token::DepositEvent: deposit
        0x0000000000000000000000000000000000000000000000000000000000000003::token::TokenDeposit: deposit
        # V2 TOKEN EVENT
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::Mint: mint
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::MintEvent: mint
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::Burn: burn
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::BurnEvent: burn
        0x0000000000000000000000000000000000000000000000000000000000000001::object::TransferEvent: transfer
        0x0000000000000000000000000000000000000000000000000000000000000001::object::Transfer: transfer
      events:
        # V1 TOKEN EVENT
        0x0000000000000000000000000000000000000000000000000000000000000003::token::MintTokenEvent:
          event_fields:
            "$.id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.id.name":
              - table: nft_marketplace_activities
                column: token_name
        0x0000000000000000000000000000000000000000000000000000000000000003::token::Mint:
          event_fields:
            "$.id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.id.name":
              - table: nft_marketplace_activities
                column: token_name
        0x0000000000000000000000000000000000000000000000000000000000000003::token::BurnTokenEvent:
          event_fields:
            "$.id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
        0x0000000000000000000000000000000000000000000000000000000000000003::token::Burn:
          event_fields:
            "$.id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
        0x0000000000000000000000000000000000000000000000000000000000000003::token::DepositEvent:
          event_fields:
            "$.id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
        0x0000000000000000000000000000000000000000000000000000000000000003::token::TokenDeposit:
          event_fields:
            "$.id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
        # V2 TOKEN EVENT
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::Mint:
          event_fields:
            "$.collection":
              - table: nft_marketplace_activities
                column: collection_id
            "$.token":
              - table: nft_marketplace_activities
                column: token_data_id
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::MintEvent:
          event_fields:
            "$.token":
              - table: nft_marketplace_activities
                column: token_data_id
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::Burn: 
          event_fields:
            "$.collection":
              - table: nft_marketplace_activities
                column: collection_id
            "$.token":
              - table: nft_marketplace_activities
                column: token_data_id
            "$.previous_owner":
              - table: nft_marketplace_activities
                column: seller
        0x0000000000000000000000000000000000000000000000000000000000000004::collection::BurnEvent: 
          event_fields:
            "$.token":
              - table: nft_marketplace_activities
                column: token_data_id 
        0x0000000000000000000000000000000000000000000000000000000000000001::object::Transfer: 
          event_fields:
            "$.from":
              - table: nft_marketplace_activities
                column: seller
            "$.to":
              - table: nft_marketplace_activities
                column: buyer
            "$.object":
              - table: nft_marketplace_activities
                column: token_data_id
        0x0000000000000000000000000000000000000000000000000000000000000001::object::TransferEvent: 
          event_fields:
            "$.from":
              - table: nft_marketplace_activities
                column: seller
            "$.to":
              - table: nft_marketplace_activities
                column: buyer
            "$.object":
              - table: nft_marketplace_activities
                column: token_data_id
    - name: "topaz"
      event_model_mapping:
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::ListEvent: list
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::DelistEvent: unlist
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BuyEvent: buy
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BidEvent: solo_bid
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelBidEvent: unlist_bid
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::SellEvent: accept_bid
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CollectionBidEvent: collection_bid  
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::FillCollectionBidEvent: accept_collection_bid
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelCollectionBidEvent: cancel_collection_bid
      events:
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::ListEvent:
          event_fields:
            "$.listing_id":
              - table: nft_marketplace_activities
                column: listing_id
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount

        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::DelistEvent:
          event_fields:
            "$.listing_id":
              - table: nft_marketplace_activities
                column: listing_id
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
        
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BuyEvent:
          event_fields:
            "$.listing_id":
              - table: nft_marketplace_activities
                column: listing_id
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
        
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::BidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::SellEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time
        
        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CollectionBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: collection_offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.collection_name":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::FillCollectionBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column:  collection_offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events::CancelCollectionBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: collection_offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.collection_name":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time