health_check_port: 8085
server_config:
  tapp_url: "https://display-engine-mirror.tapp-dex.devucc.name/api/v1"
  processor_mode:
    type: default
    initial_starting_version: 1997824036
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    # At which tx version to start indexing, usually this is the tx version when the contract was deployed
    starting_version: 1997824036
    # At which tx version to stop indexing
    # request_ending_version: 10000
    # Go to https://developers.aptoslabs.com/ to create a project and get an API token
    auth_token: "auth_token_you_can_get_from_aptos_build"
    request_name_header: ""
  db_config:
    type: postgres_config
    # do not include the ?sslmode=require in the connection string when using cloud DB, it will cause an error
    connection_string: "postgresql://username:password@neon_host/db_name"
    # we set db_pool_size to a lower number on cloud because we use a free plan
    db_pool_size: 25
  nft_marketplace_configs:
    - name: topaz
      module_address: 0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2::events
      event_model_mapping:
        ListEvent: list
        DelistEvent: unlist
        BuyEvent: buy
        BidEvent: solo_bid
        CancelBidEvent: unlist_bid
        SellEvent: accept_bid
        CollectionBidEvent: collection_bid  
        FillCollectionBidEvent: accept_collection_bid
        CancelCollectionBidEvent: cancel_collection_bid
      events:
        ListEvent:
          event_fields:
            "$.listing_id":
              - table: nft_marketplace_activities
                column: listing_id
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount

        DelistEvent:
          event_fields:
            "$.listing_id":
              - table: nft_marketplace_activities
                column: listing_id
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
        
        BuyEvent:
          event_fields:
            "$.listing_id":
              - table: nft_marketplace_activities
                column: listing_id
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
        
        BidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        CancelBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        SellEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time
        
        CollectionBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: collection_offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.collection_name":
              - table: nft_marketplace_activities
                column: collection_name
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        FillCollectionBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column:  collection_offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.seller":
              - table: nft_marketplace_activities
                column: seller
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.token_id.token_data_id.name":
              - table: nft_marketplace_activities
                column: token_name
            "$.token_id.token_data_id.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.token_id.token_data_id.collection":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time

        CancelCollectionBidEvent:
          event_fields:
            "$.bid_id":
              - table: nft_marketplace_activities
                column: collection_offer_id
            "$.amount":
              - table: nft_marketplace_activities
                column: token_amount
            "$.buyer":
              - table: nft_marketplace_activities
                column: buyer
            "$.price":
              - table: nft_marketplace_activities
                column: price
            "$.creator":
              - table: nft_marketplace_activities
                column: creator_address
            "$.collection_name":
              - table: nft_marketplace_activities
                column: collection_name
            "$.deadline":
              - table: nft_marketplace_activities
                column: expiration_time